version: "2.0"

services:
  flask:
    build:
      context: flask
    tty: true
    stdin_open: true
    environment:
      FLASK_ENV: development
      FLASK_APP: app
      PYTHONUNBUFFERED: 1
    volumes:
      - ./flask:/app
    ports:
      - "5000:5000"
    depends_on:
      - "postgres"
  postgres:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: {}
