version: "2.0"

services:
  flask:
    build:
      context: .
    tty: true
    stdin_open: true
    environment:
      FLASK_ENV: development
      FLASK_APP: app
      PORT: 3000
      DATABASE_URL: postgres://postgres@postgres/postgres
      REDIS_URL: redis://redis
      PYTHONUNBUFFERED: 1
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    command:
      - python
      - app.py
  postgres:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis
volumes:
  postgres: {}
