version: "2.0"

services:
  flask:
    build:
      context: .
    tty: true
    stdin_open: true
    environment:
      FLASK_ENV: development
      FLASK_APP: app
      PORT: 5000
      DATABASE_URL: postgres://postgres@postgres/postgres
      PYTHONUNBUFFERED: 1
    volumes:
      - ./:/app
    ports:
      - "5000:5000"
    depends_on:
      - "postgres"
  postgres:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: {}
